#mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#
#server.port=3306
#spring.thymeleaf.cache=false
#spring.datasource.name=shoppings
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/shoppings?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
#spring.datasource.username=root
#spring.datasource.password=zz091605
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=15
#spring.datasource.hikari.auto-commit=true
#spring.datasource.hikari.idle-timeout=60000
#spring.datasource.hikari.pool-name=hikariCP
#spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.connection-test-query=SELECT 1
server:
  port: 8080

spring:
  datasource:
    username: root
    password: zz091605
    url: jdbc:mysql://localhost:3306/shoppings?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    com:
      example:
        mapper : error


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml